var testRequest = {
    "vehicles":[{
        "id":"V_00",
        "depotId":0,
        "slotIndex":0,
        "modelIndex":0
    },{
        "id":"V_01",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_02",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_03",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_04",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_05",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_06",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_07",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_08",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_09",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_10",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_11",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_12",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_13",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_14",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_15",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_16",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_17",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_18",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_19",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":0
    },{
        "id":"V_20",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_21",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_22",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_23",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_24",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":1
    },{
        "id":"V_25",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_26",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_27",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_28",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_29",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":2
    },{
        "id":"V_30",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":-1
    },{
        "id":"V_31",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":-1
    },{
        "id":"V_32",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":-1
    },{
        "id":"V_33",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":-1
    },{
        "id":"V_34",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":-1
    },{
        "id":"V_35",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":-1
    },{
        "id":"V_36",
        "depotId":-1,
        "slotIndex":-1,
        "modelIndex":-1
    }],
    "depots":[]
}


